### ISSUE TITLE
Validation issue

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/tools-java#136] opened 2023-07-24 09:20 UTC
In [this SPDX document](https://github.com/tern-tools/tern/files/12104025/output.txt) (it is in JSON format, but has .txt extension because of GitHub), the SPDXID `SPDXRef-v2\"-None` is used, which contains the [invalid](https://spdx.github.io/spdx-spec/v2.3/package-information/#72-package-spdx-identifier-field) (escaped) character `"`.

This issue is not picked up by the java-tools validation.

For reference, [the issue came up here](https://github.com/tern-tools/tern/issues/1240).

**Comment by goneall** [comment] 2023-07-25 17:53
@armintaenzertng what version of the tools were you using?  I just ran verify the the above referenced file on the master version and got the following error:

```
Analysis exception processing SPDX file: No SPDX element found for SPDX ID SPDXRef-None-None
```

**Comment by armintaenzertng** [comment] 2023-07-26 06:51
Sorry for the confusion, Gary, I did not notice that the java-tools don't even get to the validation step due to the `SPDXRef-None-None` error. I deleted the offending reference, [here](https://github.com/spdx/tools-java/files/12168905/output.txt) is the "fixed" version. This seems to pick up on all issues I mentioned, though I must say that the formatting seems a bit off, especially all these "Relationship error:" parts:
```
This SPDX Document is not valid due to:
        Relationship error: Relationship error: Relationship error: Relationship error: Invalid SPDX ID: SPDXRef-v2"-None.  Must match the pattern SPDXRef-([0-9a-zA-Z\.\-\+]+)$ in v2" in v2" in 665fbbf998e4658c0a6f232f6b2e286eea9c794e8e92a529a92246fb7a7a1597 in 665fbbf998e4658c0a6f232f6b2e286eea9c794e8e92a529a92246fb7a7a1597 in d909eff282003e2d64af08633f4ae58f8cab4efc0a83b86579b4bbcb0ac90956 in d909eff282003e2d64af08633f4ae58f8cab4efc0a83b86579b4bbcb0ac90956 in golang in golang in Tern report for golang
        Relationship error: Relationship error: Relationship error: License not found for LicenseRef-45c771b in 665fbbf998e4658c0a6f232f6b2e286eea9c794e8e92a529a92246fb7a7a1597 in d909eff282003e2d64af08633f4ae58f8cab4efc0a83b86579b4bbcb0ac90956 in d909eff282003e2d64af08633f4ae58f8cab4efc0a83b86579b4bbcb0ac90956 in golang in golang in Tern report for golang
        Relationship error: Relationship error: Relationship error: License not found for LicenseRef-21495e9 in 665fbbf998e4658c0a6f232f6b2e286eea9c794e8e92a529a92246fb7a7a1597 in d909eff282003e2d64af08633f4ae58f8cab4efc0a83b86579b4bbcb0ac90956 in d909eff282003e2d64af08633f4ae58f8cab4efc0a83b86579b4bbcb0ac90956 in golang in golang in Tern report for golang
        Relationship error: Relationship error: Relationship error: License not found for LicenseRef-fa9fd02 in 665fbbf998e4658c0a6f232f6b2e286eea9c794e8e92a529a92246fb7a7a1597 in d909eff282003e2d64af08633f4ae58f8cab4efc0a83b86579b4bbcb0ac90956 in d909eff282003e2d64af08633f4ae58f8cab4efc0a83b86579b4bbcb0ac90956 in golang in golang in Tern report for golang
        Relationship error: Relationship error: Relationship error: License not found for LicenseRef-1b79b75 in 665fbbf998e4658c0a6f232f6b2e286eea9c794e8e92a529a92246fb7a7a1597 in d909eff282003e2d64af08633f4ae58f8cab4efc0a83b86579b4bbcb0ac90956 in d909eff282003e2d64af08633f4ae58f8cab4efc0a83b86579b4bbcb0ac90956 in golang in golang in Tern report for golang
        Relationship error: Relationship error: Relationship error: License not found for LicenseRef-4ccf56f in 665fbbf998e4658c0a6f232f6b2e286eea9c794e8e92a529a92246fb7a7a1597 in d909eff282003e2d64af08633f4ae58f8cab4efc0a83b86579b4bbcb0ac90956 in d909eff282003e2d64af08633f4ae58f8cab4efc0a83b86579b4bbcb0ac90956 in golang in golang in Tern report for golang
        Relationship error: Relationship error: Relationship error: License not found for LicenseRef-ca2312b in 665fbbf998e4658c0a6f232f6b2e286eea9c794e8e92a529a92246fb7a7a1597 in d909eff282003e2d64af08633f4ae58f8cab4efc0a83b86579b4bbcb0ac90956 in d909eff282003e2d64af08633f4ae58f8cab4efc0a83b86579b4bbcb0ac90956 in golang in golang in Tern report for golang
        Relationship error: Relationship error: Relationship error: License not found for LicenseRef-39c3ee0 in 665fbbf998e4658c0a6f232f6b2e286eea9c794e8e92a529a92246fb7a7a1597 in d909eff282003e2d64af08633f4ae58f8cab4efc0a83b86579b4bbcb0ac90956 in d909eff282003e2d64af08633f4ae58f8cab4efc0a83b86579b4bbcb0ac90956 in golang in golang in Tern report for golang
        Relationship error: Relationship error: Relationship error: Missing required package verification code for package 665fbbf998e4658c0a6f232f6b2e286eea9c794e8e92a529a92246fb7a7a1597 in d909eff282003e2d64af08633f4ae58f8cab4efc0a83b86579b4bbcb0ac90956 in d909eff282003e2d64af08633f4ae58f8cab4efc0a83b86579b4bbcb0ac90956 in golang in golang in Tern report for golang
        Relationship error: Relationship error: License not found for LicenseRef-1c734cf in c9b1b535fdd91a9855fb7f82348177e5f019329a58c53c47272962dd60f71fc9 in golang in golang in Tern report for golang
        Relationship error: Relationship error: License not found for LicenseRef-21495e9 in c9b1b535fdd91a9855fb7f82348177e5f019329a58c53c47272962dd60f71fc9 in golang in golang in Tern report for golang
        Relationship error: Relationship error: Missing required package verification code for package c9b1b535fdd91a9855fb7f82348177e5f019329a58c53c47272962dd60f71fc9 in golang in golang in Tern report for golang
```

**Comment by goneall** [comment] 2023-12-17 01:52
This is similar, if not a duplicate of issue #134 and the spec issue is in https://github.com/spdx/spdx-spec/issues/802.

Closing this issue.

@armintaenzertng - if I missed something, please open a new issue.

**Closed** 2023-12-17 02:50 UTC
