### ISSUE TITLE
Significant performance degradation between 1.0.3 and 1.1.3 to Verify and Convert large SPDX TAG value file

### ISSUE THREAD

**Issue by hliu168** [spdx/tools-java#100] opened 2023-01-18 16:05 UTC
It was observed that compare to tools-java-1.0.3, latest tools-java-1.1.3 has significant performance degradation when performing Verify and Convert operations on large SPDX TAG Value file.

## Input File SPDX TAG Value around 55M in size ##
 
$ ls -alh ~/Documents/ | grep Big
-rw-rw-r--   1 rliu rliu  55M Jan 18 10:41 Big-Valid-SPDX-TAG-File.spdx

## Compare Timing of Verify Operation ##

$ date && java -jar ~/Documents/tools-1.0.3/tools-java-1.0.3-jar-with-dependencies.jar Verify ~/Documents/Big-Valid-SPDX-TAG-File.spdx && date
Wed 18 Jan 2023 10:43:13 AM EST
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
This SPDX Document is valid.
Wed 18 Jan 2023 10:43:29 AM EST

#### Comment: With tools-java-1.0.3-jar-with-dependencies.jar, the Verify operation finished in almost 16 seconds ####

$ date && java -jar ~/Documents/tools-1.1.3/tools-java-1.1.3-jar-with-dependencies.jar Verify ~/Documents/Big-Valid-SPDX-TAG-File.spdx && date
Wed 18 Jan 2023 10:43:52 AM EST
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
10:43:57.777 [main] ERROR org.spdx.library.model.license.ListedLicenses - Unable to access the most current listed licenses from https://spdx.org/licenses - using locally cached licenses: I/O error reading license TOC
This SPDX Document is valid.
Wed 18 Jan 2023 10:49:36 AM EST

## Compare Timing of Convert Operation ##

$ date && java -jar ~/Documents/tools-1.0.3/tools-java-1.0.3-jar-with-dependencies.jar Convert ~/Documents/Big-Valid-SPDX-TAG-File.spdx ~/Documents/Big-Valid-SPDX-TAG-File-1.0.3.spdx.json && date
Wed 18 Jan 2023 10:51:50 AM EST
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
Wed 18 Jan 2023 10:52:04 AM EST

#### Comment: Convert took 14 seconds with tools-java-1.0.3-jar-with-dependencies.jar

$ date && ./java -jar ~/Documents/tools-1.1.3/tools-java-1.1.3-jar-with-dependencies.jar Convert ~/Documents/Big-Valid-SPDX-TAG-File.spdx ~/Documents/Big-Valid-SPDX-TAG-File-1.1.3.spdx.json && date
Wed 18 Jan 2023 10:53:42 AM EST
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
10:53:47.996 [main] ERROR org.spdx.library.model.license.ListedLicenses - Unable to access the most current listed licenses from https://spdx.org/licenses - using locally cached licenses: I/O error reading license TOC
Wed 18 Jan 2023 10:59:29 AM EST

#### Comment: Covert took 5 minutes 47 seconds with tools-java-1.1.3-jar-with-dependencies.jar

**Comment by goneall** [comment] 2023-01-18 18:05
@hliu168 Thanks for submitting the very detailed issue.  I'll look into the issue.  I do recall a [previous performance issue](https://github.com/spdx/spdx-java-tagvalue-store/issues/7) with the tag/value parser - I wonder if this might be related.

**Comment by goneall** [comment] 2023-01-18 18:10
@hliu168 I noticed in your description above the following warning:

> 10:53:47.996 [main] ERROR org.spdx.library.model.license.ListedLicenses - Unable to access the most current listed licenses from https://spdx.org/licenses - using locally cached licenses: I/O error reading license TOC

This may partially explain the difference.  This warning indicates there was a timeout on an HTTP request to the SPDX listed license website which would slow down the app by about 30 seconds or so.

Is it possible to attach the file you're testing with?  I can try it on my machine/network and see what results I get.

**Comment by hliu168** [comment] 2023-01-20 18:05
@goneall Hello Sir,

Thank you very much for your prompt reply. Please review the following observations I had with the issue.

1. Regarding the "I/O error reading license TOC timeout", it happens only in a few seconds after the tool started the Verify procedure however the whole Verify process took more than 5 minutes to finish with the tool 1.1.3.

2. So far the long time elapsed on Verify and Convert only happen if the input file is TAG Value. Even though the "I/O error reading license TOC timeout" happens on my local also for SPDX JSON format input file, the process finishes very quickly for the large input JSON file (the JSON file was converted from the TAG Value file, but the process of Verify JSON input finishes very fast).

3. Unfortunately the ~55M input file is private and I couldn't upload it here. However, I managed to find a 1M+ SPDX TAG Value file where the 1.0.3 tool took ~7 seconds to verify but the 1.1.3 tool took ~40 seconds to verify on my local.

```
$ date && java -jar tools-1.0.3/tools-java-1.0.3-jar-with-dependencies.jar Verify osquery-1.0.0.manifest.spdx && date
Fri 20 Jan 2023 12:53:55 PM EST
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
This SPDX Document is valid.
Fri 20 Jan 2023 12:54:02 PM EST

$ date && java -jar tools-1.1.3/tools-java-1.1.3-jar-with-dependencies.jar Verify osquery-1.0.0.manifest.spdx && date
Fri 20 Jan 2023 12:52:06 PM EST
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
12:52:11.694 [main] ERROR org.spdx.library.model.license.ListedLicenses - Unable to access the most current listed licenses from https://spdx.org/licenses - using locally cached licenses: I/O error reading license TOC
This SPDX Document is valid.
Fri 20 Jan 2023 12:52:45 PM EST

**Comment by hliu168** [comment] 2023-01-20 21:42
[manifest.spdx.zip](https://github.com/spdx/tools-java/files/10470385/manifest.spdx.zip)

Hello Sir,

Thank you for reading this additional message.

I was able to find this SPDX TAG Value file zipped and attached (11M zipped, ~44M unzipped) which shows a big performance difference between the old tool version 1.0.3 and the new tool version 1.1.3.

Running Verify operation with old tools-java version 1.0.3 on my local, it took around **5 minutes** to finish.

Running Verify operation with new tools-java version 1.1.3 on my local, it runs for **2 hours 30 minutes** without finishing and is still running.

Please feel free to use this file on your local and check the performance difference. Thank you and have a great day!

**Comment by goneall** [comment] 2023-01-21 04:40
@hliu168 Thanks for uploading the file.  I'm able to reproduce the problem.  I'll look into the cause over the next couple days.

**Comment by goneall** [comment] 2023-01-21 18:24
Still analyzing, but here's an update:
- The problem was introduced in version 1.0.4 - this is likely due to a [check for duplicate relationships added to the tag value parser](https://github.com/spdx/spdx-java-tagvalue-store/pull/19) is is known to have created a performance problem
- Running verify on the above attached 44MB tag/value file took 13 minutes for version 1.0.3, 824 minutes for version 1.1.3 on my machine - a 63 fold performance degradation
- Running on version 1.0.4 exceeds 3 hours (it's still running) - long enough to confirm the issue was introduced in 1.0.4

The algorithm for checking for duplicate relationships does not look very efficient.  Once I confirm this is the issue I'll look into a more efficient approach.

**Comment by goneall** [comment] 2023-01-22 02:28
I've narrowed down the problem - in the changes for version 1.0.4, [RelatedElementCollection.add](https://github.com/spdx/Spdx-Java-Library/blob/36e5ecd9e5ae878f4498b92896cf033b46b602de/src/main/java/org/spdx/library/model/RelatedElementCollection.java#L172) is now used rather extensively.  There is a defensive coding [check for duplicates](https://github.com/spdx/Spdx-Java-Library/blob/36e5ecd9e5ae878f4498b92896cf033b46b602de/src/main/java/org/spdx/library/model/RelatedElementCollection.java#L177) which is rather expensive when the collections gets very large.

Now that the problem is isolated, I'll work on a solution.  It is may involve some design changes or removing the defensive check.

**Comment by goneall** [comment] 2023-01-23 00:00
I've created to PR's which significantly improve the performance:
- https://github.com/spdx/Spdx-Java-Library/pull/144 improves the performance of collections for all serializations that use the in memory store
- https://github.com/spdx/spdx-java-tagvalue-store/pull/32 dramatically reduces the time to identify and remove duplicate relationships in the tag/value store

The combination of these PR's reduce the time it takes to verify the above attached tag/value file from 824 minutes to less than 15 seconds - a 2 order of magnitude improvement.

They are rather substantial changes, so any review of the code would be appreciated.

**Comment by eaglei15** [comment] 2023-01-23 22:32
That's great news! Is there an upcoming release of the tool with the optimization?

**Comment by goneall** [comment] 2023-01-23 23:13
> That's great news! Is there an upcoming release of the tool with the optimization?

We should be able to get a new release out this week.

**Comment by goneall** [comment] 2023-01-24 22:43
Resolved with improvements to the tag/value and Java libraries mentioned in the [above comment](https://github.com/spdx/tools-java/issues/100#issuecomment-1399646805).

**Closed by goneall** 2023-01-24 22:43 UTC
